name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Propose the problem first, then the solution.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What pain point are you facing?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should we build?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: context
    attributes:
      label: Additional context
